# Rosalind RNA: Transcribing DNA into RNA

# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

s = "TAGTCGAAGGGAATCGGGACCACATACCGGGGGACTAGGAAGTCGTATGCGTAGACTTCACTGGCAGCGATTCGTCGTGCTACGTCTTAGCGATCTTGATGTCCCCTGTCCTCCTTTCCTCGAGGTGAAGGAGAACTTGGAATGTTGCGCCGTTGCAACGTGGTGCTGGTACCCGGTGGCCGCGGAACCGCTTACGGGCAGAGTGCTGCACGATCCGGGTACATATGGCAGCCGGCTGGCAGTTGAGTCGAATGGCGCGCTGGTGGTAGTCTCCGGTCGTCCTTCACTAACGCACAGACGTCTCGTACTAGTTAATAATCAATAACTATTGCGTTACCCAACGGACTTTCACCGCACCGGGGTGCCTTTCGTCACACTTCGTCCGGAGTGTGTAGTCGTCAGTGTCCTATCGTAAGCCAACCGTCCCAGCTAAGCCAGTCGTTTCGCGCAAAGTCTTAGGGAGTAGCGCAGGTAAGATCAGTTATATGACTAGATCACAAAGGTACTAGACGCTACAGTCTGTTGTACAAGTGTAGCTCTTACCACGCATCCAGGGATACTTCAAAACATTAGGGTGGACGGTTAATGGTCGTGCATAATTACTTCTTAGGCGCAACGGGACACGGTCCAGCGCAGACGTCACGTTTAAGCAGCGTGGTATCATGGAGCCCGTCTGGGTCACCAAAGAGTCAGTGGCCGTCGACACTGTTCCCGCCCCTACGTTGTGAGCATACCACATCGTAAAAGCACTCACCAAATCGCATGCTGCGATCGTTCGCTAGTGCAGTTTACGTTCATATTCTTCTGGACTAATTTCTATTCGCAGTGAACCGAATACTAGGCTTACTGACCTCTGCGATCT"
bases = list(s)

number_of_each_base = {}

for base in bases: 
    if base in number_of_each_base: 
        number_of_each_base[base] += 1
    else:
        number_of_each_base[base] = 1

for key, value in number_of_each_base.items():
    print(key, value) 

# Result:
"""
T 215
A 194
G 229
C 224
"""
# ... which is correct - I'm not sure I did it the right way though, because return should be "[f]our integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s."
